/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftMarketplaceSol from "./NFTMarketplace.sol";
export type { nftMarketplaceSol };
export type { ERC721Collections } from "./ERC721Collections";
