/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC721Collections } from "./IERC721Collections";
export type { NFTMarketplace } from "./NFTMarketplace";
